enabled: true

afk-time-seconds: 600
warning-time-seconds: 570
cleanup-timeout-seconds: 1200
rotation-threshold: 0.01
check-interval-ticks: 100
page-size: 10

actions:
  cancel-fishing: true
  kick-player: false
  warning-message: "<red><bold>Are you afk? <yellow>Move your mouse!"
  broadcast-alert: "<yellow>%player% stopped fishing due to inactivity."
  kick-message: "<red>No AFK Fishing allowed!"
